# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b87c69c4b6a7ce64c35311e9f3f291273df4ebe05dba25ccc2f06ccb401a5d1def45566b66cacbfc8bb7704349682a4abb4e5daf85967b444ec1ac5977693cb

test:
  secret_key_base: 78071409900a34c9d9a0c1cca79d3e8c45bfc53313173f3313c7089340f25b436bb2b82d65bcae5984e475c49bf589490d5a0fb996e0aa45434fd4552d9a3096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
